#77 judgeとdrawActionの作成
a-kiyo-g-relations/typescript_202307 pull request #3
Opened 2023-07-12 03:30 UTC by r-moriya-grelations

2023-07-12 05:32 UTC, a-kiyo-g-relations requested changes

2023-07-12 05:32 UTC, a-kiyo-g-relations commented on ts_study/src/ts/drawAction.ts
> +    return cardMembers.shift();
これはDeckクラスのメソッドで良いように思います。
残りカード枚数の判定(0枚の場合どうするか)も付けておいた方が良いです。

細かいですが、戻り値の指定は必ず付与してください。

2023-07-12 05:32 UTC, a-kiyo-g-relations commented on ts_study/src/ts/judge.ts
> +  static culcMyCardsNum(myCards: Card.elements[]): number {
myCards(手札)を表すクラスを作って、そこに対して実装するのが良いかと思います。
手札クラス
└ カードの合計値メソッド
　→ 取得した数値をゲームの判定メソッドに渡す
このようなフローがまとまっているかと思います。

2023-07-12 05:32 UTC, a-kiyo-g-relations commented on ts_study/src/ts/judge.ts
> +   */
ヘッダコメントは「何を処理するメソッドか」の説明、@paramには`@param 引数名 用途`の形で記載してください。

2023-07-12 05:32 UTC, a-kiyo-g-relations commented on ts_study/src/ts/judge.ts
> +  static gameByTotalNum(totalNum: number, blackJack: boolean): Result.Status {
手札の枚数は「手札」の処理、ゲームの結果は「ゲーム」の判定なので、別クラスとして分けるのが良いかと思います。

2023-07-12 05:32 UTC, a-kiyo-g-relations commented on ts_study/src/ts/judge.ts
> +    } else if (totalNum > 21) {
21はリテラルなので定数定義した方が良いです。
空間的には「ゲーム」の判定に属するかと思います。

2023-07-12 05:32 UTC, a-kiyo-g-relations commented on ts_study/src/ts/judge.ts
> +        }
これだと9, 1, 9の順でカードが来た場合にバーストしませんか？

2023-07-12 06:46 UTC, r-moriya-grelations commented on ts_study/src/ts/drawAction.ts
> +    return cardMembers.shift();
戻り値の指定をしました。
残りカードの判定に関しては、後ほどご相談させてください。

2023-07-13 09:51 UTC, a-kiyo-g-relations requested changes

2023-07-13 09:51 UTC, a-kiyo-g-relations commented on ts_study/src/ts/game.ts
> +  static judgeByCards(InHands: InHands): Result.Status {
変数のInHandsは先頭小文字にしてください。

2023-07-13 09:51 UTC, a-kiyo-g-relations commented on ts_study/src/ts/game.ts
> +  static order = 0;
orderは「並び」を指す言葉と重複してしまうので、別の名前の方が良いかと思います。

2023-07-13 09:51 UTC, a-kiyo-g-relations commented on ts_study/src/ts/deck.ts
> +  shuffle() {
今更ですが、shuffleはprivateでも良いかなと思いました。

2023-07-13 09:51 UTC, a-kiyo-g-relations commented on ts_study/src/ts/inHands.ts
> +    let howManyAce = 0;
howは動詞形っぽく見えてしまうので「エースの数」という変数名の方が良いかと思います。

2023-07-13 09:51 UTC, a-kiyo-g-relations commented on ts_study/src/ts/inHands.ts
> +   * @returns ナチュラルブラックジャックを判定するboolean
メソッドの概要が抜けています。
また、戻り値は「ナチュラルブラックジャックの場合true」のような書き方だとより良いです。

2023-07-13 09:51 UTC, a-kiyo-g-relations commented on ts_study/src/ts/inHands.ts
> +  blackJack(): boolean {
判定系のメソッドなので、動詞始まりでisなどを付けると良いかと思います。

2023-07-13 09:51 UTC, a-kiyo-g-relations commented on ts_study/src/ts/inHands.ts
> +    let jack = false;
ハイカードの有無を持つ変数がjackなのは変かと思います。
少し例外的ですが、こういった変数名に関しては`hasAce`のような命名にしても良いです。

2023-07-13 09:51 UTC, a-kiyo-g-relations commented on ts_study/src/ts/game.ts
> +  export enum Status {
「ゲームの結果」なのと、UNDER/OVERの場合は結果と言いつつ次の操作があるので、名前空間的にはGame.Statusなどの方がわかりやすいかなと思います。
判定関連のクラスはGame.MainLogicなどにしても良いですし、Game名前空間にクラスではないメソッド・変数として定義しても良いかなと思います。

2023-07-13 09:51 UTC, a-kiyo-g-relations commented on ts_study/src/ts/game.ts
> +  static BLACK_JACK = 21;
BLACK_JACKだとブラックジャックの「何」かがわかりづらいので、ブラックジャックの数値、みたいな命名がより良いかと思います。

2023-07-13 10:03 UTC, r-moriya-grelations commented on ts_study/src/ts/game.ts
> +  static judgeByCards(InHands: InHands): Result.Status {
対応しました

2023-07-13 10:04 UTC, r-moriya-grelations commented on ts_study/src/ts/game.ts
> +  static order = 0;
turnOrderに変更

2023-07-13 10:04 UTC, r-moriya-grelations commented on ts_study/src/ts/deck.ts
> +  shuffle() {
対応

2023-07-13 10:06 UTC, r-moriya-grelations commented on ts_study/src/ts/inHands.ts
> +    let howManyAce = 0;
numberOfAceに変更

2023-07-13 10:07 UTC, r-moriya-grelations commented on ts_study/src/ts/inHands.ts
> +   * @returns ナチュラルブラックジャックを判定するboolean
対応

2023-07-13 10:08 UTC, r-moriya-grelations commented on ts_study/src/ts/inHands.ts
> +  blackJack(): boolean {
対応

2023-07-13 10:09 UTC, r-moriya-grelations commented on ts_study/src/ts/inHands.ts
> +    let jack = false;
hasAceとhasHighCardに変更

2023-07-13 10:17 UTC, r-moriya-grelations commented on ts_study/src/ts/game.ts
> +  export enum Status {
namespace Game
class MainLogic
に変更

2023-07-13 10:19 UTC, r-moriya-grelations commented on ts_study/src/ts/game.ts
> +  static BLACK_JACK = 21;
BLACK＿JACK＿NUMBERに変更

2023-07-13 10:31 UTC, a-kiyo-g-relations requested changes

2023-07-13 10:31 UTC, a-kiyo-g-relations commented on ts_study/src/ts/game.ts
> +     * @returns 手札のステータスを返す/同時にリザルトメッセージもセットする
引数のコメントを最新化してください。
また、「リザルトメッセージのセット」はおそらくなくなった機能かと思います。

2023-07-13 10:31 UTC, a-kiyo-g-relations commented on ts_study/src/ts/inHands.ts
> +   */
引数のコメントを最新化してください。

2023-07-13 10:31 UTC, a-kiyo-g-relations commented on ts_study/src/ts/inHands.ts
> +   */
引数のコメントを最新化してください。

2023-07-13 10:42 UTC, merged